"""Storage interface used by services; no dependency on file storage or FastAPI."""
from typing import Protocol

class Repository(Protocol):
    def key(self) -> bytes: ...
    def read_users(self) -> dict: ...
    def add_user(self, username: str, record: dict) -> None: ...
    def load_snapshot(self, identities: bool = True) -> tuple[dict, dict]: ...
    def save_snapshot(self, result: dict, identities: dict) -> None: ...
    def audit(self, user: dict, action: str) -> None: ...
    def audit_entries(self) -> list[dict]: ...
