import {useEffect, useMemo, useState} from 'react';
import {api, errorText} from '../../shared/api/client';

type Analytics={total:number;incomplete_cards:number;departments_without_deputy:string[];departments:string[]};
type Employee={id:string;plan_name:string;department?:string|null;plan_department:string;employment_status?:string|null;employment_type?:string|null;hire_date?:string|null;schedule_type?:string|null;work_schedule?:string|null;access_card_status?:string|null;position?:string|null};

function downloadCsv(employees:Employee[]){
 const rows=['Отдел;Статус;Тип оформления;Дата приёма;Распорядок',...employees.map(employee=>[employee.department||employee.plan_department,employee.employment_status||'active',employee.employment_type||'permanent',employee.hire_date||'',employee.schedule_type||''].map(value=>`"${value}"`).join(';'))];
 const href=URL.createObjectURL(new Blob([rows.join('\n')],{type:'text/csv;charset=utf-8'}));
 const link=document.createElement('a');link.href=href;link.download='hr-analytics.csv';link.click();URL.revokeObjectURL(href);
}
function yearsSince(value?:string|null){return value?Math.max(0,(Date.now()-new Date(value).getTime())/(365.25*24*60*60*1000)):null}

export function HrAnalytics({employees,notify,onOpen}:{employees:Employee[];notify:(message:string)=>void;onOpen:(id:string)=>void}){
 const [data,setData]=useState<Analytics|null>(null),[loading,setLoading]=useState(true),[tenureDrill,setTenureDrill]=useState<number|null>(null);
 useEffect(()=>{api<Analytics>('/api/hr/analytics').then(setData).catch(error=>notify(errorText(error))).finally(()=>setLoading(false))},[]);
 const departments=useMemo(()=>Object.entries(employees.reduce<Record<string,number>>((result,employee)=>{const name=employee.department||employee.plan_department;result[name]=(result[name]||0)+1;return result},{})).sort((a,b)=>b[1]-a[1]),[employees]);
 const employed=employees.filter(employee=>(employee.employment_status||'active')==='active').length;
 const probation=employees.filter(employee=>employee.employment_type==='probation').length;
 const leave=employees.filter(employee=>employee.employment_status==='leave').length;
 const blocked=employees.filter(employee=>/блок/i.test(employee.access_card_status||'')||employee.employment_status==='inactive').length;
 const tenureGroups=useMemo(()=>{const groups:[Employee[],Employee[],Employee[],Employee[]]=[[],[],[],[]];employees.forEach(employee=>{const years=yearsSince(employee.hire_date);if(years===null)return;if(years<1)groups[0].push(employee);else if(years<3)groups[1].push(employee);else if(years<5)groups[2].push(employee);else groups[3].push(employee)});return groups},[employees]);
 const formats=useMemo(()=>Object.entries(employees.reduce<Record<string,number>>((result,employee)=>{const names:Record<string,string>={fixed:'Фиксированный',free:'Свободный',flexible:'Гибкий'};const name=names[employee.schedule_type||'']||employee.work_schedule||'Не указан';result[name]=(result[name]||0)+1;return result},{})).sort((a,b)=>b[1]-a[1]),[employees]);
 const percent=(value:number)=>employees.length?`${(value/employees.length*100).toFixed(1)}%`:'0%';
 return <section className="hr-analytics-view">
  <div className="hr-content-head"><div><p className="eyebrow">КАДРОВЫЕ ПОКАЗАТЕЛИ</p><h2>Сводные отчёты по персоналу ({employees.length} сотрудников)</h2><p>Оперативная аналитика штата, контроль испытательных сроков, СКУД и выгрузка для руководства.</p></div><div className="hr-module-actions"><button className="primary" onClick={()=>downloadCsv(employees)}>Экспорт в Excel (.xlsx)</button><button onClick={()=>window.print()}>Сформировать PDF отчёт</button></div></div>
  {loading?<p role="status">Загружаем кадровую аналитику…</p>:data&&<><div className="hr-kpi-row hr-analytics-kpis"><article><span>Всего в базе</span><b>{data.total}</b><small>100% штата</small></article><article><span>Активные</span><b>{employed}</b><small>{percent(employed)} от штата</small></article><article><span>Испыт. срок</span><b>{probation}</b><small>текущий период</small></article><article><span>В отпуске</span><b>{leave}</b><small>текущий период</small></article><article><span>Заблокировано</span><b>{blocked}</b><small>СКУД или статус сотрудника</small></article></div><div className="hr-report-grid"><section className="card"><div className="hr-report-heading"><h3>Распределение численности по отделам</h3><small>{departments.length} отделов</small></div><div className="hr-bars hr-bars-compact">{departments.map(([name,count])=><div key={name}><span>{name}</span><i><b style={{width:`${Math.max(4,count/Math.max(1,employees.length)*100)}%`}}/></i><strong>{count} чел. <small>({percent(count)})</small></strong></div>)}</div></section><div className="hr-report-aside"><section className="card"><h3>Стаж работы сотрудников</h3><div className="hr-tenure-grid">{[['Менее 1 года','Адаптационный период'],['От 1 до 3 лет','Основной костяк'],['От 3 до 5 лет','Опытные специалисты'],['Более 5 лет','Ветераны компании']].map(([label,note],index)=><button type="button" className="hr-tenure-card" title="Нажмите, чтобы открыть список сотрудников" key={label} onClick={()=>setTenureDrill(index)}><span>{label}</span><b>{tenureGroups[index].length} чел.</b><small>{note}</small></button>)}</div></section><section className="card"><h3>Форматы работы персонала</h3><div className="hr-format-list">{formats.map(([name,count])=><div key={name}><span>{name}</span><b>{count} чел. <small>({percent(count)})</small></b></div>)}</div></section></div></div></>}
  {tenureDrill!==null&&<div className="modal-backdrop" role="presentation" onMouseDown={()=>setTenureDrill(null)}><section className="hr-drill-modal" role="dialog" aria-modal="true" aria-label="Сотрудники по стажу" onMouseDown={event=>event.stopPropagation()}><header><h3>{['Менее 1 года','От 1 до 3 лет','От 3 до 5 лет','Более 5 лет'][tenureDrill]}</h3><button className="modal-close" onClick={()=>setTenureDrill(null)} aria-label="Закрыть">×</button></header><div className="table-scroll"><table><thead><tr><th>Сотрудник</th><th>Отдел</th><th>Должность</th><th>Дата приёма</th></tr></thead><tbody>{tenureGroups[tenureDrill].map(employee=><tr key={employee.id}><td><button className="link-button" onClick={()=>{setTenureDrill(null);onOpen(employee.id)}}>{employee.plan_name}</button></td><td>{employee.department||employee.plan_department}</td><td>{employee.position||'—'}</td><td>{employee.hire_date}</td></tr>)}</tbody></table></div></section></div>}
 </section>
}
