import {useEffect,useMemo,useState} from 'react';
import {api,ApiError,errorText} from '../../shared/api/client';
import type {Role} from '../../shared/types';
type HrEmployee={id:string;plan_name:string;plan_department:string;position?:string|null;employment_status?:string|null;in_current_plan:boolean;access_card_status?:string|null};
const EDITORS:Role[]=['admin','hr'];
export function HrPage({role,notify}:{role:Role;notify:(message:string)=>void}){
 const [items,setItems]=useState<HrEmployee[]>([]),[selected,setSelected]=useState<HrEmployee|null>(null),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[position,setPosition]=useState('');
 const load=()=>{setLoading(true);api<{items:HrEmployee[]}>('/api/hr/employees').then(r=>setItems(r.items)).catch(e=>{if(!(e instanceof ApiError&&e.status===503))notify(errorText(e))}).finally(()=>setLoading(false))};
 useEffect(load,[]);
 const filtered=useMemo(()=>items.filter(e=>`${e.plan_name} ${e.plan_department} ${e.position||''}`.toLowerCase().includes(query.toLowerCase())),[items,query]);
 async function save(){if(!selected)return;try{const updated=await api<HrEmployee>(`/api/hr/employees/${selected.id}`,{method:'PATCH',body:JSON.stringify({position})});setItems(prev=>prev.map(e=>e.id===updated.id?updated:e));setSelected(updated);notify('Карточка сохранена')}catch(e){notify(errorText(e))}}
 return <section className="card hr-page"><div className="pagehead"><div><p className="eyebrow">КАДРОВЫЙ УЧЁТ</p><h2>Реестр сотрудников</h2><p>ФИО и отдел берутся из первичного источника «План».</p></div><button onClick={load}>Обновить</button></div><div className="toolbar"><input aria-label="Поиск в кадровом реестре" placeholder="Поиск по ФИО, отделу, должности" value={query} onChange={e=>setQuery(e.target.value)}/><small>{filtered.length} записей</small></div>{loading?<p role="status">Загрузка кадрового реестра…</p>:<div className="table-scroll"><table><thead><tr><th>Фамилия Имя</th><th>Отдел</th><th>Должность</th><th>Статус</th><th>СКУД</th></tr></thead><tbody>{filtered.map(e=><tr key={e.id} tabIndex={0} onClick={()=>{setSelected(e);setPosition(e.position||'')}} onKeyDown={event=>event.key==='Enter'&&setSelected(e)}><td><button className="link-button" onClick={event=>{event.stopPropagation();setSelected(e);setPosition(e.position||'')}}>{e.plan_name}</button></td><td>{e.plan_department}</td><td>{e.position||'—'}</td><td>{e.in_current_plan?'В текущем плане':'Нет в текущем плане'}</td><td>{e.access_card_status||'—'}</td></tr>)}</tbody></table></div>}{selected&&<div className="modal-backdrop" role="dialog" aria-modal="true"><div className="modal card"><button className="modal-close" onClick={()=>setSelected(null)} aria-label="Закрыть">×</button><p className="eyebrow">КАРТОЧКА СОТРУДНИКА</p><h3>{selected.plan_name}</h3><p>{selected.plan_department} · Источник ФИО и отдела: План</p><label>Должность<input disabled={!EDITORS.includes(role)} value={position} onChange={e=>setPosition(e.target.value)}/></label>{EDITORS.includes(role)&&<button className="primary" onClick={save}>Сохранить</button>}</div></div>}</section>;
}
